version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - prealloc
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - performance
        - style
    gosec:
      excludes:
        - G404
    govet:
      enable-all: true
    revive:
      rules:
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: package-comments
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
